const TEST = {
    SAVE: 'TEST_SAVE',
}

const AUTH = {
    TOKEN: 'AUTH_TOKEN',
    REMOVE: 'AUTH_REMOVE',
}

const COMMON = {
    API_REQUEST: 'API_REQUEST',
    ON_CUSTOMER_DETAILS_SUCCESS: 'ON_CUSTOMER_DETAILS_SUCCESS',
    ON_CUSTOMER_DETAILS_FAIL: 'ON_CUSTOMER_DETAILS_FAIL',
    ON_CUSTOMER_DETAILS_LOAD: 'ON_CUSTOMER_DETAILS_LOAD',
    ON_CUSTOMER_NOMINEE_SUCCESS: 'ON_CUSTOMER_NOMINEE_SUCCESS',
    ON_CUSTOMER_NOMINEE_FAIL: 'ON_CUSTOMER_NOMINEE_FAIL',
    ON_CUSTOMER_NOMINEEY_LOAD: 'ON_CUSTOMER_NOMINEEY_LOAD', 
    ON_REQUEST_STATUS_LOAD: 'ON_REQUEST_STATUS_LOAD',
    ON_REQUEST_STATUS_SUCCESS: 'ON_REQUEST_STATUS_SUCCESS',
    ON_REQUEST_STATUS_FAIL: 'ON_REQUEST_STATUS_FAIL',
}

const DEPOSITE = {
    ON_DEPOSITE_LIST_SUCCESS: 'ON_DEPOSITE_LIST_SUCCESS',
    ON_DEPOSITE_LIST_FAIL: 'ON_DEPOSITE_LIST_FAIL',
    ON_DEPOSITE_LIST_LOAD: 'ON_DEPOSITE_LIST_LOAD',
    ON_FD_SUMMARY_SUCCESS: 'ON_FD_SUMMARY_SUCCESS',
    ON_FD_SUMMARY_FAIL: 'ON_FD_SUMMARY_FAIL',
    ON_FD_SUMMARY_LOAD: 'ON_FD_SUMMARY_LOAD',
    ON_FD_LOAN_SUCCESS: 'ON_FD_LOAN_SUCCESS',
    ON_FD_LOAN_FAIL: 'ON_FD_LOAN_FAIL',
    ON_FD_LOAN_LOAD: 'ON_FD_LOAN_LOAD',
    ON_APPLY_LOAN_LOAD: 'ON_APPLY_LOAN_LOAD',
    ON_APPLY_LOAN_SUCCESS: 'ON_APPLY_LOAN_SUCCESS',
    ON_APPLY_LOAN_FAIL: 'ON_APPLY_LOAN_FAIL',

}

const TYPES = {
    TEST, AUTH, COMMON, DEPOSITE
}

export default TYPES;