const TEST = {
    SAVE: 'TEST_SAVE',
}

const AUTH = {
    TOKEN: 'AUTH_TOKEN',
}

const COMMON = {
    API_REQUEST: 'API_REQUEST',
}

const DEPOSITE = {
    ON_DEPOSITE_LIST_SUCCESS: 'ON_DEPOSITE_LIST_SUCCESS',
    ON_DEPOSITE_LIST_FAIL: 'ON_DEPOSITE_LIST_FAIL',
    ON_DEPOSITE_LIST_LOAD: 'ON_DEPOSITE_LIST_LOAD',
}


const TYPES = {
    TEST, AUTH, COMMON, DEPOSITE
}

export default TYPES;