export const NAVIGATION = {
    DASHBOARD: 'DASHBOARD',
    DEPOSITE_LIST: 'DEPOSITE_LIST',
    PROFILE: 'PROFILE',
    FD_DETAILS: 'FD_DETAILS',
    MY_LOANS: 'MY_LOANS',
    SERVICE_REQUEST: 'SERVICE_REQUEST',
    COMMING_SOON: 'COMMING_SOON'
}