export const NAVIGATION = {
    DASHBOARD: 'DASHBOARD',
    DEPOSITE_LIST: 'DEPOSITE_LIST',
    PROFILE: 'PROFILE',
    FD_DETAILS: 'FD_DETAILS',
    MY_LOANS: 'MY_LOANS',
    SERVICE_REQUEST: 'SERVICE_REQUEST',
    COMMING_SOON: 'COMMING_SOON',
    CERTIFICATE_LIST: 'CERTIFICATE_LIST',
    VIEW_CERTIFICATE: 'VIEW_CERTIFICATE',
}